CREATE TABLE enderecos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	cep VARCHAR(255),
	cidade VARCHAR(255),
	estado VARCHAR(2),
	is_principal BOOLEAN,
	logradouro VARCHAR(255),
    numero VARCHAR(20),
    pessoa_id BIGINT,
    PRIMARY KEY (id),
	CONSTRAINT fk_enderecos_pessoas foreign key(pessoa_id) references pessoas(id)
);